### PR TITLE
Track `Cargo.lock` in git

### PR DESCRIPTION
**Pull request by SpriteOvO**
Hi! Thanks for your great work on this project!

I'm packaging this crate to ArchLinux AUR (https://aur.archlinux.org/). According to the Rust documentation ([ref](https://doc.rust-lang.org/cargo/faq.html#why-have-cargolock-in-version-control)), the `Cargo.lock` should be tracked in version control, and ArchLinux packaging guideline also recommends build Rust crate with `--locked` Cargo option, which requires a `Cargo.lock` file in the directory.

This PR ran `cargo update` to fetch the latest dependencies info, and added tracking for `Cargo.lock` to the git.

### CODE REVIEW

**Comment by ssrlive** [comment]
This option is redundant for me and the file `Cargo.lock`  is too large. So I hope you handle it yourself in your use case.

**Comment by SpriteOvO** [comment]
> This option is redundant for me and the file `Cargo.lock` is too large.

This makes sense for *reproducible build*.

> So I hope you handle it yourself in your use case.

I'll add `Cargo.lock` to the AUR repo for now, it would be nice to upstream it.

Thanks for your fast response.

**Comment by ssrlive** [comment]
I don't want a small change to require a large amount of code to be submitted.

Just keep your needs on your branch.

If you want to keep the code synchronized with the upstream, add a synchronization script to your branch yourself.

**Comment by SpriteOvO** [comment]
> I don't want a small change to require a large amount of code to be submitted.

It won't.

`Cargo.lock` locks the dependencies version, this file will only be modified when you edit `[dependencies]` in `Cargo.toml` or explicitly execute `cargo update`.

**Comment by ssrlive** [comment]
What we use is to only track the large version number. Every time we run the `cargo update` command, it will cause significant changes in the `Cargo.lock` file, which is very annoying for developers. 

We assume that each of our dependent libraries will not have compatibility issues due to changes in minor versions.

https://github.com/tun2proxy/tun2proxy/blob/b8c22db037af267f498d80d945a3a0326ae8e291/Cargo.toml#L16-L23

**Pull request closed without merging**
